
#ifndef _KEYBOX_ERROR_CODE_INCLUDE_
#define _KEYBOX_ERROR_CODE_INCLUDE_

#define KEYBOX_ERROR_OK 0
#define KEYBOX_ERROR_GENERAL -1
#define KEYBOX_ERROR_WALLET_NOT_INITIALIZED -2
#define KEYBOX_ERROR_WALLET_LOCKED -3
#define KEYBOX_ERROR_INVALID_PARAMETER -4
#define KEYBOX_ERROR_NOT_SUPPORTED -5
#define KEYBOX_ERROR_USER_CANCELLED -6
#define KEYBOX_ERROR_CLIENT_ISSUE -7
#define KEYBOX_ERROR_SERVER_ISSUE -8
#define KEYBOX_ERROR_DEVICE_BUSY -9

#endif
